#!/usr/bin/env node
/**
 * Build per-hook Markdown pages from wp-hooks/generator JSON.
 *
 * Reads data/<plugin>/actions.json and data/<plugin>/filters.json
 * and writes docs/<plugin>/hooks/*.md plus sidebars/<plugin>.hooks.json.
 */

import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {normalizeHookName, slugifyHookName} from './normalize-hook-name.mjs';
import {renderHookPage, renderHooksIndex, renderSidebarItems} from './render-hook.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const requestedPlugin = process.argv[2];

const catalog = JSON.parse(fs.readFileSync(path.join(root, 'plugins.json'), 'utf8'));
const plugins = Array.isArray(catalog.plugins) ? catalog.plugins : [];

let generatedPlugins = 0;

for (const plugin of plugins) {
  if (plugin.status !== 'available') {
    continue;
  }
  if (requestedPlugin && plugin.id !== requestedPlugin) {
    continue;
  }

  const dataDir = path.join(root, 'data', plugin.id);
  const actionsPath = path.join(dataDir, 'actions.json');
  const filtersPath = path.join(dataDir, 'filters.json');
  if (!fs.existsSync(actionsPath) && !fs.existsSync(filtersPath)) {
    console.warn(`No hook JSON for ${plugin.id}; skipped.`);
    continue;
  }

  const hooks = [
    ...loadHooks(actionsPath, 'action'),
    ...loadHooks(filtersPath, 'filter'),
  ];

  const prepared = prepareHooks(hooks, plugin);
  writePlugin(plugin, prepared);
  generatedPlugins += 1;
  console.log(`Generated ${prepared.length} hook page(s) for ${plugin.id}.`);
}

if (generatedPlugins === 0) {
  console.error('No plugin hook data was generated.');
  process.exit(1);
}

/**
 * @param {string} filePath
 * @param {string} fallbackType
 * @returns {object[]}
 */
function loadHooks(filePath, fallbackType) {
  if (!fs.existsSync(filePath)) {
    return [];
  }

  const document = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  if (!document || !Array.isArray(document.hooks)) {
    throw new Error(`${path.relative(root, filePath)} is missing a hooks array.`);
  }

  return document.hooks.map((hook) => ({
    ...hook,
    type: hook.type || fallbackType,
  }));
}

/**
 * @param {object[]} hooks
 * @param {{id: string, pluginPrefix?: string}} plugin
 */
function prepareHooks(hooks, plugin) {
  const prefix = plugin.pluginPrefix || '';
  const usedSlugs = new Set();

  const prepared = hooks.map((hook) => {
    const name = normalizeHookName(hook.name, prefix);
    let slug = slugifyHookName(name);
    if (usedSlugs.has(slug)) {
      let suffix = 2;
      while (usedSlugs.has(`${slug}-${suffix}`)) {
        suffix += 1;
      }
      slug = `${slug}-${suffix}`;
    }
    usedSlugs.add(slug);

    const type = hook.type || 'filter';
    return {
      hook,
      name,
      slug,
      type,
      summary: String(hook.doc?.description || '').replace(/\s+/g, ' ').trim(),
    };
  });

  prepared.sort((a, b) => {
    const key = (name) => name.replace(/[{}]/g, '').toLowerCase();
    return key(a.name).localeCompare(key(b.name)) || a.slug.localeCompare(b.slug);
  });
  return prepared;
}

/**
 * @param {{id: string, repository?: object | null}} plugin
 * @param {ReturnType<typeof prepareHooks>} prepared
 */
function writePlugin(plugin, prepared) {
  const hooksDir = path.join(root, 'docs', plugin.id, 'hooks');
  fs.mkdirSync(hooksDir, {recursive: true});

  for (const entry of fs.readdirSync(hooksDir)) {
    if (entry.endsWith('.md') || entry.endsWith('.mdx')) {
      fs.unlinkSync(path.join(hooksDir, entry));
    }
  }

  const indexHooks = prepared.map((entry) => ({
    name: entry.name,
    slug: entry.slug,
    type: entry.type,
    summary: entry.summary,
  }));

  fs.writeFileSync(
    path.join(hooksDir, 'README.md'),
    [
      '# Generated hook pages',
      '',
      `This directory is generated by \`scripts/generate-hooks.mjs\` from \`data/${plugin.id}/actions.json\` and \`data/${plugin.id}/filters.json\`.`,
      '',
      'Do not edit these files by hand. Update the JSON source, or the generator, then run `npm run generate`.',
      '',
    ].join('\n'),
  );

  fs.writeFileSync(path.join(hooksDir, 'index.md'), renderHooksIndex(indexHooks, plugin.id));

  for (const entry of prepared) {
    const exampleFile = path.join(root, 'examples', plugin.id, entry.slug, 'index.md');
    const exampleImport = fs.existsSync(exampleFile)
      ? `@site/examples/${plugin.id}/${entry.slug}/index.md`
      : null;

    const page = renderHookPage(entry.hook, {
      normalizedName: entry.name,
      slug: entry.slug,
      plugin,
      exampleImport,
    });
    fs.writeFileSync(path.join(hooksDir, `${entry.slug}.md`), page);
  }

  const sidebarPath = path.join(root, 'sidebars', `${plugin.id}.hooks.json`);
  fs.mkdirSync(path.dirname(sidebarPath), {recursive: true});
  fs.writeFileSync(sidebarPath, `${JSON.stringify(renderSidebarItems(indexHooks), null, 2)}\n`);
}
