/**
 * Render one hook reference page and the shared index sections.
 * Pages are MDX, so `{` outside code spans is escaped.
 */

const CALLEE = {
  action: 'do_action',
  filter: 'apply_filters',
  action_reference: 'do_action_ref_array',
  filter_reference: 'apply_filters_ref_array',
};

const TYPE_LABEL = {
  action: 'Action',
  filter: 'Filter',
  action_reference: 'Action',
  filter_reference: 'Filter',
};

/**
 * @param {string} markdown
 * @returns {string}
 */
export function escapeMdx(markdown) {
  const parts = String(markdown).split(/(```[\s\S]*?```|`[^`\n]*`)/g);
  return parts
    .map((part) => {
      if (part.startsWith('`')) {
        return part;
      }
      return part.replace(/[{}]/g, (char) => (char === '{' ? "{'{'}" : "{'}'}"));
    })
    .join('');
}

/**
 * @param {object} hook
 * @param {string} normalizedName
 * @returns {string}
 */
export function buildSignature(hook, normalizedName) {
  const params = paramTags(hook);
  const count = Number.isInteger(hook.args) ? hook.args : params.length;
  const argNames = [];

  for (let index = 0; index < count; index += 1) {
    const variable = params[index]?.variable;
    if (typeof variable === 'string' && variable.trim()) {
      const name = variable.trim();
      argNames.push(name.startsWith('$') ? name : `$${name}`);
    } else {
      argNames.push(`$arg${index + 1}`);
    }
  }

  const type = hook.type || 'filter';
  const callee = CALLEE[type] || 'apply_filters';
  const quotedName = `'${normalizedName.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

  if (type === 'action_reference' || type === 'filter_reference') {
    return `${callee}( ${quotedName}, array( ${argNames.join(', ')} ) );`;
  }

  return `${callee}( ${[quotedName, ...argNames].join(', ')} );`;
}

/**
 * @param {object} hook
 * @param {{repository?: {url?: string, branch?: string} | null}} plugin
 * @returns {{label: string, url: string | null}}
 */
export function sourceLocation(hook, plugin) {
  let file = typeof hook.file === 'string' ? hook.file : '';
  let line = integerOrNull(hook.line);

  const inline = file.match(/^(.*?):(\d+)$/);
  if (inline && line == null) {
    file = inline[1];
    line = Number(inline[2]);
  }

  const endLine = integerOrNull(hook.end_line);
  let label = file || 'Unknown file';
  if (line != null && endLine != null && endLine !== line) {
    label = `${file}:${line}-${endLine}`;
  } else if (line != null) {
    label = `${file}:${line}`;
  }

  const repository = plugin.repository;
  if (!repository?.url || !file) {
    return {label, url: null};
  }

  const branch = repository.branch || 'main';
  const base = String(repository.url).replace(/\/+$/, '');
  const hash = line != null ? `#L${line}` : '';
  return {
    label,
    url: `${base}/blob/${branch}/${file}${hash}`,
  };
}

/**
 * @param {object} hook
 * @param {object} options
 * @param {string} options.normalizedName
 * @param {string} options.slug
 * @param {{repository?: {url?: string, branch?: string} | null}} options.plugin
 * @param {string | null | undefined} options.exampleMarkdown Example body. Front matter is already removed.
 * @param {{name: string, slug: string}[] | undefined} options.relatedExampleLinks
 * @returns {string}
 */
export function renderHookPage(hook, options) {
  const {normalizedName, plugin} = options;
  const exampleMarkdown = typeof options.exampleMarkdown === 'string' ? options.exampleMarkdown.trim() : '';
  const relatedExampleLinks = Array.isArray(options.relatedExampleLinks) ? options.relatedExampleLinks : [];
  const summary = oneLine(hook.doc?.description || '');
  const longDescription = String(hook.doc?.long_description || '').trim();
  const typeLabel = TYPE_LABEL[hook.type] || 'Hook';
  const signature = buildSignature(hook, normalizedName);
  const source = sourceLocation(hook, plugin);
  const params = paramTags(hook);
  const sinceTags = tagsNamed(hook, 'since');
  const deprecated = tagsNamed(hook, 'deprecated');

  const lines = [
    '---',
    `title: ${yamlString(normalizedName)}`,
    `sidebar_label: ${yamlString(normalizedName)}`,
    `description: ${yamlString(summary || `${typeLabel} ${normalizedName}`)}`,
    '---',
    '',
    '{/* Generated by scripts/generate-hooks.mjs. Do not edit. */}',
    '',
    `**Type:** ${typeLabel}`,
    '',
  ];

  if (Array.isArray(hook.aliases) && hook.aliases.length > 0) {
    const aliases = hook.aliases
      .map((alias) => String(alias).trim())
      .filter((alias) => alias && alias !== normalizedName)
      .map((alias) => `\`${alias}\``);
    if (aliases.length > 0) {
      lines.push(`**Aliases:** ${aliases.join(', ')}`, '');
    }
  }

  if (deprecated.length > 0) {
    const detail = deprecated
      .map((tag) => oneLine(tag.content || ''))
      .filter(Boolean)
      .join(' ');
    lines.push(':::warning Deprecated', '', escapeMdx(detail || 'This hook is deprecated.'), '', ':::', '');
  }

  if (summary) {
    lines.push(escapeMdx(summary), '');
  }

  if (longDescription && longDescription !== summary) {
    lines.push(escapeMdx(longDescription), '');
  }

  lines.push('## Signature', '', '```php', signature, '```', '', '## Parameters', '');

  if (params.length === 0 && !(hook.args > 0)) {
    lines.push('This hook does not pass any parameters.', '');
  } else {
    lines.push('| Name | Type | Description |', '| --- | --- | --- |');
    const rowCount = Math.max(params.length, Number(hook.args) || 0);
    for (let index = 0; index < rowCount; index += 1) {
      const param = params[index];
      const variable = param?.variable
        ? param.variable.startsWith('$')
          ? param.variable
          : `$${param.variable}`
        : `$arg${index + 1}`;
      const types = Array.isArray(param?.types) && param.types.length > 0 ? param.types : ['mixed'];
      const typeCell = types.map((type) => `\`${escapePipes(type)}\``).join(' \\| ');
      const description = escapePipes(oneLine(param?.content || ''));
      lines.push(`| \`${variable}\` | ${typeCell} | ${escapeMdx(description)} |`);
    }
    lines.push('');
  }

  lines.push('## Since', '');
  if (sinceTags.length === 0) {
    lines.push('Not documented.', '');
  } else {
    for (const tag of sinceTags) {
      const version = oneLine(tag.content || '');
      const note = oneLine(tag.description || '');
      if (version && note) {
        lines.push(`- \`${escapePipes(version)}\` — ${escapeMdx(note)}`);
      } else if (version) {
        lines.push(`- \`${escapePipes(version)}\``);
      }
    }
    lines.push('');
  }

  lines.push('## Source', '');
  if (source.url) {
    lines.push(`[\`${source.label}\`](${source.url})`, '');
  } else {
    lines.push(`\`${source.label}\``, '');
  }

  if (exampleMarkdown || relatedExampleLinks.length > 0) {
    lines.push('## Examples', '');
    if (exampleMarkdown) {
      lines.push(escapeMdx(exampleMarkdown), '');
    }
    for (const link of relatedExampleLinks) {
      lines.push(escapeMdx(`See example on [\`${link.name}\`](./${link.slug}).`), '');
    }
  }

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trim()}\n`;
}

/**
 * @param {{name: string, slug: string, type: string, summary: string}[]} hooks
 * @param {string} pluginId
 * @returns {string}
 */
export function renderHooksIndex(hooks, pluginLabel) {
  const actions = hooks.filter((hook) => hook.type === 'action' || hook.type === 'action_reference');
  const filters = hooks.filter((hook) => hook.type !== 'action' && hook.type !== 'action_reference');

  const lines = [
    '---',
    'title: Hooks',
    'sidebar_label: All hooks',
    `description: ${yamlString(`Actions and filters in ${pluginLabel}.`)}`,
    '---',
    '',
    '{/* Generated by scripts/generate-hooks.mjs. Do not edit. */}',
    '',
    `Actions and filters in ${pluginLabel}.`,
    '',
  ];

  lines.push(...renderHookTable('Actions', actions));
  lines.push(...renderHookTable('Filters', filters));

  if (hooks.length === 0) {
    lines.push('No hooks are listed yet.', '');
  }

  return `${lines.join('\n').trim()}\n`;
}

/**
 * @param {{name: string, slug: string, type: string, summary: string}[]} hooks
 * @returns {object[]}
 */
export function renderSidebarItems(hooks) {
  const actions = hooks.filter((hook) => hook.type === 'action' || hook.type === 'action_reference');
  const filters = hooks.filter((hook) => hook.type !== 'action' && hook.type !== 'action_reference');

  /** @type {object[]} */
  const items = [
    {
      type: 'doc',
      id: 'hooks/index',
      label: 'All hooks',
    },
  ];

  if (actions.length > 0) {
    items.push({
      type: 'category',
      label: 'Actions',
      items: actions.map(sidebarDoc),
    });
  }

  if (filters.length > 0) {
    items.push({
      type: 'category',
      label: 'Filters',
      items: filters.map(sidebarDoc),
    });
  }

  return items;
}

/**
 * @param {string} heading
 * @param {{name: string, slug: string, summary: string}[]} hooks
 * @returns {string[]}
 */
function renderHookTable(heading, hooks) {
  if (hooks.length === 0) {
    return [];
  }

  const lines = [`## ${heading}`, '', '| Hook | Description |', '| --- | --- |'];
  for (const hook of hooks) {
    const summary = escapeMdx(escapePipes(oneLine(hook.summary || '')));
    lines.push(`| [\`${hook.name}\`](./${hook.slug}) | ${summary} |`);
  }
  lines.push('');
  return lines;
}

/**
 * @param {{slug: string, name: string}} hook
 */
function sidebarDoc(hook) {
  return {
    type: 'doc',
    id: `hooks/${hook.slug}`,
    label: hook.name,
  };
}

/**
 * @param {object} hook
 */
function paramTags(hook) {
  return tagsNamed(hook, 'param');
}

/**
 * @param {object} hook
 * @param {string} name
 */
function tagsNamed(hook, name) {
  const tags = hook.doc?.tags;
  if (!Array.isArray(tags)) {
    return [];
  }
  return tags.filter((tag) => tag && tag.name === name);
}

/**
 * @param {unknown} value
 * @returns {number | null}
 */
function integerOrNull(value) {
  if (typeof value === 'number' && Number.isInteger(value)) {
    return value;
  }
  if (typeof value === 'string' && /^[0-9]+$/.test(value)) {
    return Number(value);
  }
  return null;
}

/**
 * @param {string} value
 * @returns {string}
 */
function oneLine(value) {
  return String(value).replace(/\s+/g, ' ').trim();
}

/**
 * @param {string} value
 * @returns {string}
 */
function escapePipes(value) {
  return String(value).replace(/\|/g, '\\|');
}

/**
 * @param {string} value
 * @returns {string}
 */
function yamlString(value) {
  return JSON.stringify(oneLine(value));
}
