import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import hookItems from './eu-vat.hooks.json';

const sidebars: SidebarsConfig = {
  euVat: [
    'index',
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Guides',
        description: 'Guides for using EU-VAT Assistant hooks.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Hooks',
      items: hookItems as SidebarsConfig[string],
    },
  ],
};

export default sidebars;
